(() => {
'use strict';
const c=document.getElementById('game'),x=c.getContext('2d',{alpha:true}),map=document.getElementById('map-layer');
const start=document.getElementById('start'),screen=document.getElementById('start-screen'),note=document.getElementById('load-note'),guide=document.getElementById('guide'),joy=document.getElementById('joystick'),knob=document.getElementById('joystick-knob'),resetBtn=document.getElementById('reset');
const REF={w:1448,h:1086},SPAWN={x:724,y:1015},SPEED=155,DPRMAX=2,DRAWH=65;
const areas=[{t:'p',p:[[590,1086],[858,1086],[885,955],[905,825],[910,730],[885,655],[835,605],[615,605],[570,660],[565,780],[575,925]]},{t:'e',cx:724,cy:535,rx:300,ry:174},{t:'p',p:[[575,500],[875,500],[885,420],[870,340],[860,245],[850,190],[598,190],[588,250],[575,345],[565,430]]}],blocks=[{t:'e',cx:724,cy:545,rx:128,ry:84}];
const files={idle:'./assets/sprites/shion/shion_idle.png',down:'./assets/sprites/shion/shion_walk_down.png',up:'./assets/sprites/shion/shion_walk_up.png',left:'./assets/sprites/shion/shion_walk_left.png',right:'./assets/sprites/shion/shion_walk_right.png'};
const imgs={},keys=new Set(),stick={on:false,id:null,ox:0,oy:0,x:0,y:0};
let manifest,world={w:REF.w,h:REF.h},scale={x:1,y:1},cw=1,ch=1,dpr=1,ready=false,run=false,last=0,anim=0;
const player={x:SPAWN.x,y:SPAWN.y,dir:'up',moving:false,frame:0},camera={x:SPAWN.x,y:SPAWN.y-42,zoom:1};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function poly(px,py,p){let inside=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const[xi,yi]=p[i],[xj,yj]=p[j];if(((yi>py)!==(yj>py))&&px<(xj-xi)*(py-yi)/((yj-yi)||.000001)+xi)inside=!inside}return inside}
function inside(px,py,a){return a.t==='e'?((px-a.cx)/a.rx)**2+((py-a.cy)/a.ry)**2<=1:poly(px,py,a.p)}
function canStand(px,py){const rx=px/scale.x,ry=py/scale.y,walk=(a,b)=>a>4&&b>4&&a<REF.w-4&&b<REF.h-4&&areas.some(z=>inside(a,b,z))&&!blocks.some(z=>inside(a,b,z));return walk(rx,ry)&&walk(rx-6,ry)&&walk(rx+6,ry)&&walk(rx,ry+3)}
function loadImage(src){return new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=()=>no(new Error('画像を読み込めません: '+src));i.src=src})}
function waitMap(){return new Promise((ok,no)=>{if(map.complete&&map.naturalWidth)return ok(map);map.addEventListener('load',()=>ok(map),{once:true});map.addEventListener('error',()=>no(new Error('マップを読み込めません')),{once:true})})}
function resize(){const r=c.getBoundingClientRect();cw=Math.max(1,r.width);ch=Math.max(1,r.height);dpr=Math.min(devicePixelRatio||1,DPRMAX);c.width=Math.round(cw*dpr);c.height=Math.round(ch*dpr);x.setTransform(dpr,0,0,dpr,0,0);camera.zoom=clamp(Math.min(cw/620,ch/560),.88,1.22)}
function reset(){player.x=SPAWN.x*scale.x;player.y=SPAWN.y*scale.y;player.dir='up';player.moving=false;player.frame=0;camera.x=player.x;camera.y=player.y-42*scale.y}
function input(){let vx=0,vy=0;if(keys.has('ArrowLeft')||keys.has('a'))vx--;if(keys.has('ArrowRight')||keys.has('d'))vx++;if(keys.has('ArrowUp')||keys.has('w'))vy--;if(keys.has('ArrowDown')||keys.has('s'))vy++;if(stick.on){vx+=stick.x;vy+=stick.y}const l=Math.hypot(vx,vy);return l>1?{x:vx/l,y:vy/l}:{x:vx,y:vy}}
function update(dt){const v=input();player.moving=Math.hypot(v.x,v.y)>.08;if(!player.moving){player.frame=0;anim=0;return}player.dir=Math.abs(v.x)>Math.abs(v.y)?(v.x<0?'left':'right'):(v.y<0?'up':'down');const sp=SPEED*((scale.x+scale.y)/2),nx=player.x+v.x*sp*dt,ny=player.y+v.y*sp*dt;if(canStand(nx,ny)){player.x=nx;player.y=ny}else{if(canStand(nx,player.y))player.x=nx;if(canStand(player.x,ny))player.y=ny}anim+=dt;if(anim>=.12){anim=0;player.frame=(player.frame+1)%4}}
function cam(dt){const vw=cw/camera.zoom,vh=ch/camera.zoom,hw=vw/2,hh=vh/2,tx=clamp(player.x,hw,Math.max(hw,world.w-hw)),ty=clamp(player.y-42*scale.y,hh,Math.max(hh,world.h-hh)),e=1-Math.exp(-7*dt);camera.x+=(tx-camera.x)*e;camera.y+=(ty-camera.y)*e}
function origin(){const vw=cw/camera.zoom,vh=ch/camera.zoom;return{x:clamp(camera.x-vw/2,0,Math.max(0,world.w-vw)),y:clamp(camera.y-vh/2,0,Math.max(0,world.h-vh))}}
function drawPlayer(){const fw=manifest.cell_size.width,fh=manifest.cell_size.height,base=manifest.baseline_y,s=DRAWH/fh,dw=fw*s,dh=fh*s,dx=player.x-dw/2,dy=player.y-base*s;let img,sx;if(player.moving){img=imgs[player.dir];sx=player.frame*fw}else{img=imgs.idle;sx=({down:0,up:1,left:2,right:3}[player.dir])*fw}x.imageSmoothingEnabled=false;x.drawImage(img,sx,0,fw,fh,dx,dy,dw,dh)}
function draw(){const o=origin();map.style.transformOrigin='0 0';map.style.transform=`translate3d(${-o.x*camera.zoom}px,${-o.y*camera.zoom}px,0) scale(${camera.zoom})`;x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,cw,ch);x.save();x.scale(camera.zoom,camera.zoom);x.translate(-o.x,-o.y);x.fillStyle='rgba(12,10,30,.22)';x.beginPath();x.ellipse(player.x,player.y+1,10,3.5,0,0,Math.PI*2);x.fill();drawPlayer();x.restore()}
function loop(now){if(!run)return;const dt=Math.min(last?(now-last)/1000:0,.05);last=now;update(dt);cam(dt);draw();requestAnimationFrame(loop)}
function begin(e){e&&e.preventDefault();if(!ready||run)return;run=true;screen.hidden=true;guide.hidden=false;resetBtn.hidden=false;resize();reset();last=performance.now();draw();requestAnimationFrame(loop);setTimeout(()=>guide.hidden=true,6500)}
function down(e){if(!run)return;const r=c.getBoundingClientRect(),px=e.clientX-r.left,py=e.clientY-r.top;if(px>cw*.68)return;stick.on=true;stick.id=e.pointerId;stick.ox=px;stick.oy=py;stick.x=0;stick.y=0;joy.hidden=false;joy.style.left=px+'px';joy.style.top=py+'px';c.setPointerCapture?.(e.pointerId);guide.hidden=true;e.preventDefault()}
function move(e){if(!stick.on||e.pointerId!==stick.id)return;const r=c.getBoundingClientRect(),px=e.clientX-r.left,py=e.clientY-r.top,max=38;let dx=px-stick.ox,dy=py-stick.oy,l=Math.hypot(dx,dy);if(l>max){dx=dx/l*max;dy=dy/l*max}stick.x=dx/max;stick.y=dy/max;knob.style.transform=`translate(${dx}px,${dy}px)`;e.preventDefault()}
function end(e){if(!stick.on||e.pointerId!==stick.id)return;stick.on=false;stick.id=null;stick.x=stick.y=0;knob.style.transform='translate(0,0)';joy.hidden=true}
start.addEventListener('click',begin);resetBtn.addEventListener('click',reset);c.addEventListener('pointerdown',down,{passive:false});c.addEventListener('pointermove',move,{passive:false});c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end);addEventListener('resize',()=>{resize();if(ready)draw()});addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','w','a','s','d'].includes(k)){keys.add(k);guide.hidden=true;e.preventDefault()}},{passive:false});addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));
(async()=>{try{note.textContent='マップと正式シオンスプライトを読み込んでいます…';const m=await fetch('./assets/sprites/shion/shion_sprite_manifest.json');if(!m.ok)throw new Error('スプライト設定を読み込めません');manifest=await m.json();const arr=await Promise.all([waitMap(),...Object.entries(files).map(async([k,src])=>{imgs[k]=await loadImage(src)})]);const mp=arr[0];world={w:mp.naturalWidth,h:mp.naturalHeight};scale={x:world.w/REF.w,y:world.h/REF.h};map.style.width=world.w+'px';map.style.height=world.h+'px';const fw=manifest.cell_size.width,fh=manifest.cell_size.height;for(const d of ['down','up','left','right'])if(imgs[d].naturalWidth!==fw*4||imgs[d].naturalHeight!==fh)throw new Error(d+'歩行画像サイズ不正');if(imgs.idle.naturalWidth!==fw*4||imgs.idle.naturalHeight!==fh)throw new Error('待機画像サイズ不正');ready=true;resize();reset();draw();start.disabled=false;start.textContent='星の国へ';note.textContent=`正式シオン実装済み / 4方向4フレーム / ${world.w}×${world.h}`}catch(e){console.error(e);start.disabled=true;start.textContent='起動できません';note.textContent=e.message}})();
})();
