(() => {
  "use strict";
  const shell=document.getElementById("game-shell"),map=document.getElementById("map-layer");if(!shell||!map)return;
  const REF={w:1448,h:1086},worldLayers=[...document.querySelectorAll("[data-scene-world]")],objectLayers=[...document.querySelectorAll("[data-scene-object]")],validGateStates=new Set(["normal","unstable","event"]),params=new URLSearchParams(location.search),config=document.currentScript?.dataset||{},DEPTH_URL=config.depthUrl||"./assets/maps/star-country-gate-garden-depth.json",layout=window.TarotSceneLayout;
  let lastCamera="",actorSurface,foregroundSurface,gateState="normal",debugOutput;const masks=new Map();let depthZones={behindForegroundAreas:[],backgroundAreas:[],baselineAreas:[]};const debug=params.get("sceneDebug")==="1";
  function normalizePolys(list){return(Array.isArray(list)?list:[]).filter(a=>a?.type==="poly"&&Array.isArray(a.points)&&a.points.length>=3&&a.points.every(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite)))}
  function normalizeBaselines(list){return(Array.isArray(list)?list:[]).filter(a=>a?.type==="baseline"&&Array.isArray(a.points)&&a.points.length===2&&a.points.every(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite))).map(a=>({...a,rearDepth:Number.isFinite(a.rearDepth)?Math.max(1,a.rearDepth):180}))}
  async function loadDepthZones(){try{const r=await fetch(`${DEPTH_URL}${DEPTH_URL.includes("?")?"&":"?"}t=${Date.now()}`,{cache:"no-store"});if(!r.ok)return;const d=await r.json();if(d?.map!=="star-country-gate-garden"||d?.referenceSize?.width!==REF.w||d?.referenceSize?.height!==REF.h)return;depthZones={behindForegroundAreas:normalizePolys(d.behindForegroundAreas),backgroundAreas:normalizePolys(d.backgroundAreas),baselineAreas:normalizeBaselines(d.baselineAreas)}}catch(e){console.warn("前後関係データを読み込めませんでした",e)}}
  const footIn=(foot,areas)=>areas.some(a=>layout.contains(foot,a));
  function behindBaseline(foot,a){const[p0,p1]=a.points,minX=Math.min(p0[0],p1[0]),maxX=Math.max(p0[0],p1[0]);if(foot.x<minX||foot.x>maxX)return false;const dx=p1[0]-p0[0],t=Math.abs(dx)<.001?.5:(foot.x-p0[0])/dx,lineY=p0[1]+(p1[1]-p0[1])*t;return foot.y<lineY&&foot.y>=lineY-a.rearDepth}
  const footBehindBaseline=foot=>depthZones.baselineAreas.some(a=>behindBaseline(foot,a));
  function prepareOccluders(foreground){for(const area of layout.occluders){const[x,y,w,h]=area.bounds,s=document.createElement("canvas");s.width=w;s.height=h;const p=s.getContext("2d");p.translate(-x,-y);layout.trace(p,area.points);p.clip();if(area.source==="foreground")p.drawImage(foreground,0,0);else{const layer=document.querySelector(area.source==="gate"?".scene-gate-base":".scene-fountain-base"),b=layer.dataset;p.drawImage(layer.querySelector("img"),Number(b.worldX),Number(b.worldY),Number(b.worldW),Number(b.worldH))}masks.set(area.id,{surface:s,x,y,w,h})}}
  function drawMaskedActor(ctx,actor,scale,density,draw){const foot={x:actor.x/scale.x,y:actor.y/scale.y},forcedFront=footIn(foot,depthZones.backgroundAreas),baselineBehind=!forcedFront&&footBehindBaseline(foot),forcedBehind=!forcedFront&&(baselineBehind||footIn(foot,depthZones.behindForegroundAreas)),active=forcedFront?[]:layout.activeOccluders(foot);if(!forcedBehind&&!active.length){draw(ctx);return}actorSurface||=document.createElement("canvas");const left=actor.x-84*scale.x,top=actor.y-110*scale.y,width=168*scale.x,height=142*scale.y,pw=Math.ceil(width*density),ph=Math.ceil(height*density);if(actorSurface.width!==pw||actorSurface.height!==ph){actorSurface.width=pw;actorSurface.height=ph}const paint=actorSurface.getContext("2d");paint.setTransform(1,0,0,1,0,0);paint.clearRect(0,0,pw,ph);paint.setTransform(pw/width,0,0,ph/height,-left*pw/width,-top*ph/height);draw(paint);paint.save();paint.globalCompositeOperation="destination-out";if(forcedBehind&&foregroundSurface)paint.drawImage(foregroundSurface,0,0,REF.w*scale.x,REF.h*scale.y);for(const area of active){const m=masks.get(area.id);if(m)paint.drawImage(m.surface,m.x*scale.x,m.y*scale.y,m.w*scale.x,m.h*scale.y)}paint.restore();ctx.drawImage(actorSurface,0,0,pw,ph,left,top,width,height)}
  function drawDebug(ctx,actors,scale,zoom){if(!debug)return;ctx.save();ctx.scale(scale.x,scale.y);ctx.lineWidth=1/zoom;ctx.font="10px monospace";for(const a of layout.occluders){ctx.strokeStyle="#529aff";layout.trace(ctx,a.footArea.points);ctx.stroke()}for(const a of depthZones.baselineAreas){ctx.strokeStyle="#ffe277";ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(...a.points[0]);ctx.lineTo(...a.points[1]);ctx.stroke();ctx.strokeStyle="#ffe27788";ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(a.points[0][0],a.points[0][1]-a.rearDepth);ctx.lineTo(a.points[1][0],a.points[1][1]-a.rearDepth);ctx.stroke()}ctx.setLineDash([]);for(const a of depthZones.behindForegroundAreas){ctx.strokeStyle="#d88cff";layout.trace(ctx,a.points);ctx.stroke()}for(const a of depthZones.backgroundAreas){ctx.strokeStyle="#62dfff";layout.trace(ctx,a.points);ctx.stroke()}const states={};for(const[name,actor]of Object.entries(actors)){const foot={x:actor.x/scale.x,y:actor.y/scale.y};states[name]={...foot,manual:footIn(foot,depthZones.backgroundAreas)?"background":footBehindBaseline(foot)?"baseline-behind":footIn(foot,depthZones.behindForegroundAreas)?"behind":"auto",occluders:layout.activeOccluders(foot).map(a=>a.id)}}ctx.restore();debugOutput.textContent="SCENE 2.0 · "+Object.entries(states).map(([n,s])=>`${n}:${s.manual}/${s.occluders.join(",")||"clear"}`).join(" · ");debugOutput.dataset.state=JSON.stringify({gate:layout.gate,depthZones,actors:states})}
  function setGateState(next="normal"){const s=validGateStates.has(next)?next:"normal";gateState=s;shell.dataset.gateState=s;return s}
  function syncCamera({world,origin,zoom}){const sig=[world.w,world.h,origin.x,origin.y,zoom].join(",");if(sig===lastCamera)return;lastCamera=sig;const transform=`translate3d(${-origin.x*zoom}px,${-origin.y*zoom}px,0) scale(${zoom})`;for(const l of worldLayers){l.style.width=`${world.w}px`;l.style.height=`${world.h}px`;l.style.transform=transform}const sx=world.w/REF.w,sy=world.h/REF.h;for(const l of objectLayers){const{worldX:x,worldY:y,worldW:w,worldH:h}=l.dataset;l.style.left="0px";l.style.top="0px";l.style.width=`${Number(w)*sx}px`;l.style.height=`${Number(h)*sy}px`;l.style.transform=`translate3d(${(Number(x)*sx-origin.x)*zoom}px,${(Number(y)*sy-origin.y)*zoom}px,0) scale(${zoom})`}}
  function waitImage(img){if(img.complete&&img.naturalWidth)return Promise.resolve(img);return new Promise((res,rej)=>{img.addEventListener("load",()=>res(img),{once:true});img.addEventListener("error",()=>rej(new Error("庭園レイヤーを読み込めません")),{once:true})})}
  const ready=Promise.all([loadDepthZones(),...[map,...document.querySelectorAll(".scene-world-layer img, .scene-object img")].map(waitImage)]).then(()=>{const bg=document.querySelector(".scene-background canvas"),fg=document.querySelector(".scene-foreground canvas");layout.paintBackground(bg.getContext("2d"),map,document.querySelector(".scene-star-sky img"));layout.paintForeground(fg.getContext("2d"),document.querySelector(".scene-foreground img"));foregroundSurface=fg;prepareOccluders(fg);for(const l of document.querySelectorAll(".scene-waterfall")){const img=l.querySelector("img"),p=l.querySelector("canvas").getContext("2d");p.drawImage(img,0,0,REF.w,REF.h);layout.removeLegacyGate(p);l.style.maskImage=`url("${img.src}")`;l.style.webkitMaskImage=`url("${img.src}")`}layout.splitCrystal(document.querySelector(".scene-crystal-core").getContext("2d"),document.querySelector(".scene-crystal-ring").getContext("2d"),document.querySelector(".scene-fountain-crystal img"));shell.dataset.sceneReady="true"});ready.catch(()=>{});
  window.addEventListener("tarot-breaker:gate-state",e=>setGateState((typeof e.detail==="string"?e.detail:e.detail?.state)||"normal"));if(debug){shell.classList.add("scene-debug");debugOutput=document.createElement("output");debugOutput.id="scene-status";debugOutput.className="scene-status";shell.appendChild(debugOutput)}setGateState(params.get("gateState")||"normal");window.TarotSceneEffects=Object.freeze({ready,syncCamera,drawMaskedActor,drawDebug,setGateState,getGateState:()=>gateState,getDepthZones:()=>({behindForegroundAreas:[...depthZones.behindForegroundAreas],backgroundAreas:[...depthZones.backgroundAreas],baselineAreas:[...depthZones.baselineAreas]}),referenceSize:Object.freeze({...REF})});window.dispatchEvent(new CustomEvent("tarot-breaker:scene-ready",{detail:{gateState}}));
})();