'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const code=fs.readFileSync('future-vision-audio.js','utf8');
function harness({off=false,reject=false,seekFail=false,late=false,unloaded=false,mismatch=false,syncThrow=false,noContext=false,seeking=false,suspended=false,asyncSeek=false}={}){
 let now=0,frame=0;const callbacks=new Map(),listeners={},media=[];const signal=new AbortController().signal;
 const window={__TAROT_DEV_STAGE3__:true,TarotAudio:{enabled:!off},addEventListener:(n,f)=>listeners[n]=f,removeEventListener:()=>{}};
 class Audio{constructor(src){this.src=src;this.paused=true;this.readyState=unloaded?0:1;this.duration=210;this._time=0;this.seeking=seeking;this.plays=0;this.listeners={};media.push(this);}get currentTime(){return this._time}set currentTime(t){if(seekFail)throw Error('seek');if(asyncSeek){this.seekTarget=t;this.seeking=true;}else if(!mismatch)this._time=t;}pause(){this.paused=true;}play(){this.plays++;if(syncThrow)throw Error('syncplay');this.paused=false;if(reject)return Promise.reject(Error('denied'));if(late)return new Promise(r=>this.complete=()=>{this.paused=false;r();});return Promise.resolve();}addEventListener(n,f){this.listeners[n]=f}removeEventListener(n){delete this.listeners[n]}}
 class Context{constructor(){this.currentTime=0;this.state=suspended?'suspended':'running';this.destination={}}resume(){return Promise.resolve()}createMediaElementSource(){return{connect(){}}}createGain(){return{connect(){},gain:{value:0,cancelScheduledValues(){}}}}}
 if(!noContext)window.AudioContext=Context;const document={hidden:false,addEventListener:(n,f)=>listeners[n]=f,removeEventListener:()=>{}};
 const ctx={window,document,location:{search:'?dev=star-gate-full'},URLSearchParams,Audio,queueMicrotask,requestAnimationFrame:f=>{callbacks.set(++frame,f);return frame},cancelAnimationFrame:i=>callbacks.delete(i)};vm.runInNewContext(code,ctx);
 const failures=[],api=window.TarotFutureVisionAudio.create({clock:{now:()=>now},signal,failures,id:1});
 return{api,media,failures,window,document,listeners,step(ms){now+=ms;const jobs=[...callbacks.values()];callbacks.clear();jobs.forEach(f=>f(now));}};
}
const flush=async()=>{await Promise.resolve();await Promise.resolve();};
test('Arcana audio loses the normal world, nearly vanishes, then atomically switches to fix',async()=>{
 const h=harness();await flush();h.api.ruinsVisible();h.step(250);await flush();let s=h.api.getState();
 assert.equal(s.tracks.ruins.time,1.8);assert.ok(Math.abs(s.tracks.ruins.gain-.70*10**(-6.48/20))<1e-8);
 h.api.arcanaAnomalyStart();s=h.api.getState();assert.equal(s.phase,'ARCANA_MICRO');assert.equal(s.tracks.ruins.weight,.94);assert.equal(s.tracks.fix.weight,0);
 h.api.arcanaInfection(.5);s=h.api.getState();assert.equal(s.phase,'ARCANA_INFECTION');assert.ok(Math.abs(s.tracks.ruins.weight-.72)<1e-8);assert.equal(s.tracks.fix.weight,0);assert.equal(s.tracks.fix.paused,true);
 h.api.arcanaBreak();s=h.api.getState();assert.equal(s.phase,'ARCANA_BREAK');assert.equal(s.tracks.ruins.weight,.06);assert.equal(s.tracks.fix.weight,0);
 h.api.arcanaRewrite();await flush();s=h.api.getState();assert.equal(s.phase,'FIX');assert.equal(h.media[0].paused,true);assert.equal(s.tracks.fix.time,20);assert.equal(s.tracks.fix.weight,1);assert.ok(Math.abs(s.tracks.fix.gain-.50*10**(-5.23/20))<1e-8);
 h.api.setLevel(.125);h.api.pause('FULL_WHITE');assert.ok(h.media.every(m=>m.paused));assert.equal(h.api.getState().tracks.fix.gain,0);
 h.api.resumeWhite();h.api.setLevel(1);await flush();s=h.api.getState();assert.equal(s.tracks.ruins.time,1.8);assert.equal(s.tracks.ruins.mix,.25);assert.equal(s.tracks.fix.paused,true);
 h.api.pause('BLACK_CUT');assert.ok(h.media.every(m=>m.paused));h.api.dispose();
});test('OFF never starts media; errors degrade to silence',async()=>{const off=harness({off:true});off.api.ruinsVisible();off.step(250);assert.ok(off.media.every(m=>m.plays===0&&m.paused));assert.equal(off.api.getState().tracks.ruins.gain,0);off.api.dispose();for(const options of [{reject:true},{seekFail:true}]){const h=harness(options);await flush();h.api.ruinsVisible();await flush();assert.ok(h.failures.length);assert.equal(h.api.getState().tracks.ruins.gain,0);h.api.dispose();}});
test('pagehide pauses even when hidden is false; disposal prevents delayed play resurrection',async()=>{const h=harness({late:true});h.api.ruinsVisible();h.step(250);h.listeners.pagehide();assert.ok(h.media.every(m=>m.paused));h.api.dispose();h.media.forEach(m=>m.complete?.());await flush();assert.ok(h.media.every(m=>m.paused));assert.equal(h.api.getState().tracks.ruins.gain,0);});
test('end of track falls over last1500ms without looping; bounded rewrite play fails silent',async()=>{
 const h=harness();await flush();h.api.ruinsVisible();h.step(250);await flush();h.media[0]._time=209.25;h.step(1);const s=h.api.getState();assert.ok(Math.abs(s.tracks.ruins.gain-.5*.70*10**(-6.48/20))<1e-8);assert.equal(h.media[0].loop,false);h.api.dispose();
 const late=harness({late:true});late.api.arcanaRewrite();late.step(10001);assert.ok(late.failures.some(f=>f.includes('timeout')));assert.equal(late.api.getState().tracks.fix.gain,0);late.api.dispose();
});test('integration routes semantic erosion cues without ordinary BGM source replacement',()=>{
 const s=fs.readFileSync('star-gate-anomaly.js','utf8');
 assert.match(s,/if\(i===1\)session\.futureAudio\?\.ruinsVisible\(\)/);
 assert.match(s,/phase\('MICRO_ANOMALY'\);current\.futureAudio\?\.arcanaAnomalyStart\?\.\(\)/);
 assert.match(s,/current\.futureAudio\?\.arcanaInfection\?\.\(p\)/);
 assert.match(s,/phase\('SEMANTIC_BREAK'\);current\.futureAudio\?\.arcanaBreak\?\.\(\)/);
 assert.match(s,/current\.futureAudio\?\.arcanaRewrite\?\.\(\)/);
 assert.doesNotMatch(s,/futureAudio\?\.transform(Start|End)?/);
 assert.match(s,/audioLevel:k=>current\.futureAudio\?\.setLevel\(k\)/);assert.match(s,/resumeFutureAudio\(\)\{current\.futureAudio\?\.resumeWhite\(\)/);assert.match(s,/audio\.setLevel\(0\);safeResume\(current\.p0\.audio,'P0'\)/);assert.doesNotMatch(s,/audio\.src\s*=/);
});test('unloaded metadata deadline invalidates late callbacks and malformed seek stays silent',async()=>{const h=harness({unloaded:true});await flush();h.api.ruinsVisible();h.step(10001);assert.ok(h.failures.some(f=>f.includes('timeout')));h.media[0].readyState=1;h.media[0].listeners.loadedmetadata?.();await flush();assert.equal(h.media[0].paused,true);assert.equal(h.api.getState().tracks.ruins.gain,0);h.api.dispose();for(const options of [{mismatch:true},{syncThrow:true},{noContext:true}]){const f=harness(options);await flush();f.api.ruinsVisible();f.media[0].listeners.seeked?.();f.step(250);await flush();assert.ok(f.failures.length);assert.equal(f.api.getState().tracks.ruins.gain,0);assert.equal(f.media[0].paused,true);f.api.dispose();}});
test('mid-erosion musicOFF pauses the desired source and rewrite later owns only fix',async()=>{
 const h=harness();await flush();h.api.ruinsVisible();h.step(250);await flush();h.api.arcanaAnomalyStart();h.api.arcanaInfection(.5);await flush();
 h.window.TarotAudio.enabled=false;h.step(10);assert.ok(h.media.every(m=>m.paused));assert.equal(h.api.getState().tracks.fix.gain,0);
 h.window.TarotAudio.enabled=true;h.listeners.click();await flush();assert.equal(h.media[0].paused,false);assert.equal(h.media[1].paused,true);
 h.api.arcanaBreak();h.api.arcanaRewrite();await flush();assert.equal(h.media[0].paused,true);assert.equal(h.media[1].paused,false);h.api.dispose();
});test('hidden preserves atomic rewrite phase and does not seek or restart the fixed track',async()=>{
 const h=harness();await flush();h.api.ruinsVisible();h.step(250);await flush();h.api.arcanaAnomalyStart();h.api.arcanaInfection(1);h.api.arcanaBreak();h.api.arcanaRewrite();await flush();
 const before=h.api.getState();assert.equal(before.phase,'FIX');assert.equal(before.tracks.fix.time,20);assert.equal(before.tracks.fix.weight,1);
 h.document.hidden=true;h.listeners.visibilitychange();assert.ok(h.media.every(m=>m.paused));assert.equal(h.api.getState().phase,'FIX');
 h.document.hidden=false;h.listeners.visibilitychange();h.listeners.click();await flush();const after=h.api.getState();assert.equal(after.phase,'FIX');assert.equal(after.tracks.fix.time,20);assert.equal(after.tracks.fix.weight,1);assert.equal(h.media[0].paused,true);h.api.dispose();
});test('native seeking is gain0 until seeked and stalled seek times out; suspended graph is degradation',async()=>{const h=harness({seeking:true});await flush();h.api.ruinsVisible();h.step(250);assert.equal(h.api.getState().tracks.ruins.gain,0);h.media[0].seeking=false;h.media[0].listeners.seeked();await flush();h.step(1);assert.ok(h.api.getState().tracks.ruins.gain>0);h.api.dispose();const stalled=harness({seeking:true});await flush();stalled.api.ruinsVisible();stalled.step(10001);assert.ok(stalled.failures.some(f=>f.includes('timeout')));assert.equal(stalled.api.getState().tracks.ruins.gain,0);stalled.api.dispose();const suspended=harness({suspended:true});await flush();assert.ok(suspended.failures.some(f=>f.includes('context-state')));assert.ok(suspended.media.every(m=>m.paused));suspended.api.dispose();});
test('old play fulfillment does not pause a newer allowed request; disposed error cannot rewrite report',async()=>{const h=harness({late:true});h.api.ruinsVisible();const older=h.media[0].complete;h.document.hidden=true;h.listeners.visibilitychange();h.document.hidden=false;h.listeners.visibilitychange();h.listeners.click();await flush();const newer=h.media[0].complete;newer();await flush();assert.equal(h.media[0].paused,false);older();await flush();assert.equal(h.media[0].paused,false);h.api.dispose();const before=h.failures.length;h.media[0].listeners.error();assert.equal(h.failures.length,before);});

test('pagehide with hiddenfalse rejects late play before disposal, and pageshow restores saved position',async()=>{const h=harness({late:true});h.api.ruinsVisible();h.step(250);const pending=h.media[0].complete;h.listeners.pagehide();pending();await flush();h.step(16);assert.equal(h.media[0].paused,true);assert.equal(h.api.getState().tracks.ruins.gain,0);assert.equal(h.api.getState().suspended,true);h.listeners.pageshow();h.media[0].complete();await flush();h.step(16);assert.equal(h.media[0].paused,false);assert.equal(h.media[0].currentTime,1.8);assert.ok(h.api.getState().tracks.ruins.gain>0);h.api.dispose();});

test('pending initial gesture unlock cannot revive fix on pagehide before monitor or disposal',async()=>{const h=harness({late:true});const originalFixUnlock=h.media[1].complete;h.listeners.pagehide();originalFixUnlock();await flush();assert.equal(h.media[1].paused,true);assert.equal(h.api.getState().tracks.fix.gain,0);assert.equal(h.api.getState().suspended,true);h.api.dispose();});

test('native asynchronous setter may remain0 until seeked without false failure',async()=>{const h=harness({asyncSeek:true});await flush();h.api.ruinsVisible();h.step(250);assert.equal(h.media[0].currentTime,0);assert.equal(h.failures.length,0);assert.equal(h.api.getState().tracks.ruins.gain,0);h.media[0]._time=h.media[0].seekTarget;h.media[0].seeking=false;h.media[0].listeners.seeked();await flush();h.step(1);assert.equal(h.media[0].currentTime,1.8);assert.equal(h.failures.length,0);assert.ok(h.api.getState().tracks.ruins.gain>0);h.api.dispose();});

test('late initial unlock cannot restart an explicitly stopped black or white source',async()=>{for(const phase of ['ENTRY_BLACK','FULL_WHITE','BLACK_CUT']){const h=harness({late:true});const pending=h.media.map(m=>m.complete);h.api.pause(phase);pending.forEach(f=>f());await flush();assert.ok(h.media.every(m=>m.paused));assert.ok(Object.values(h.api.getState().tracks).every(t=>t.gain===0));h.api.dispose();}});

test('initial unlock late fulfillment after a forced black pause stays paused before disposal',async()=>{const h=harness({late:true});const initial=h.media.map(m=>m.complete);h.api.pause('ENTRY_BLACK');initial.forEach(f=>f());await flush();assert.ok(h.media.every(m=>m.paused));assert.equal(h.api.getState().tracks.ruins.gain,0);assert.equal(h.api.getState().tracks.fix.gain,0);h.api.dispose();});
