const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const SOURCE=fs.readFileSync(require('node:path').join(__dirname,'../star-gate-aftermath.js'),'utf8');
function harness({dev=true,restoreFails=false,unlockFails=false,inputRemains=false,npcRemains=false}={}){
 const handlers={},docHandlers={},nodes={},calls=[],motions=[],shown=[];const facing={};let focused=false,time=0,owner=null,departed=false,ui,following=true,nextTimer=0;const timers=new Map();
 const actors={shion:{x:810,y:145},shiopon:{x:805,y:170},lumiere:{x:815,y:212}};const visibility={shion:1,shiopon:0,lumiere:0};
 function node(){return {hidden:false,children:[],classList:{items:new Set(),add(c){this.items.add(c)},contains(c){return this.items.has(c)},toggle(c,v){v?this.items.add(c):this.items.delete(c)}},listeners:{},append(...a){this.children.push(...a);for(const n of a)if(n.id)nodes[n.id]=n},setAttribute(){},addEventListener(n,f){this.listeners[n]=f},remove(){this.removed=true},textContent:'',type:''};}
 const shell=node();nodes['game-shell']=shell;const canvas=node();canvas.getBoundingClientRect=()=>({left:0,top:0});nodes['game']=canvas;
 const state=()=>({actors:JSON.parse(JSON.stringify(actors)),visibility:{...visibility},lumiereRect:{left:actors.lumiere.x-780,right:actors.lumiere.x-700},viewport:{width:390,height:844},owner,inputSuspended:!!owner||inputRemains,npcSuspended:!!owner||npcRemains,following,lumiereEnabled:!departed});
 const scene={capture(){calls.push('capture');return {actors:JSON.parse(JSON.stringify(actors)),visibility:{...visibility},departed,following,weakLight:false}},lock(o){owner=o;calls.push('lock')},unlock(o){calls.push('unlock');if(unlockFails||owner!==o)return false;owner=null;return true},clearInput(){calls.push('clear')},getState:state,hitTestActor(x){return x<50?'shiopon':'lumiere'},setActorVisibility(actor,value){visibility[actor]=value;return true},face(actor,target){facing[actor]=target},gameplayCamera(){focused=false},focusGate(){focused=true},perform(c){motions.push(c);actors[c.actor]={...actors[c.actor],...c.target};return {promise:Promise.resolve()}},flightPose(p){actors.lumiere={...actors.lumiere,...p}},setLumiereDeparted(v=true){departed=v},pause(){},async restore(a){if(restoreFails)throw Error('restore');Object.assign(actors,a.actors);Object.assign(visibility,a.visibility);departed=a.departed;following=a.following;calls.push('restore')},verify:()=>({completed:!restoreFails&&!!owner})};
 const window={__TAROT_DEV_STAGE3__:dev,TarotAftermathScene:scene,TarotFutureStage3:{createClock(signal){return {now:()=>time,assert(){if(signal.aborted)throw Error('abort')},wait(ms){if(signal.aborted)return Promise.reject(Error('abort'));time+=ms;return Promise.resolve()},dispose(){}}}},TarotDialogueUI:{create(o){ui={show(line){ui.line=line;shown.push({text:line.text,actor:line.actor,facing:{...facing},focused});},hide(){},destroy(){},elements:{layer:node()},advance:o.onAdvance};return ui}},addEventListener(n,f){(handlers[n]??=[]).push(f)},removeEventListener(n,f){handlers[n]=(handlers[n]||[]).filter(v=>v!==f)},dispatchEvent(e){if(e.type==='tarot-breaker:shiopon-follow-stop')following=false;if(e.type==='tarot-breaker:shiopon-follow-start')following=true;for(const f of handlers[e.type]||[])f(e)},setInterval(f){const id=++nextTimer;timers.set(id,f);return id},clearInterval(id){timers.delete(id)}};
 const document={hidden:false,body:node(),getElementById:id=>nodes[id],querySelector:()=>null,createElement:node,addEventListener(n,f){(docHandlers[n]??=[]).push(f)},removeEventListener(n,f){docHandlers[n]=(docHandlers[n]||[]).filter(v=>v!==f)}};
 vm.runInNewContext(SOURCE,{window,document,AbortController,CustomEvent:class{constructor(type,{detail}={}){this.type=type;this.detail=detail}}});
 return {window,calls,shown,nodes,state,advancedCount:0,movePlayer(x,y){actors.shion.x=x;actors.shion.y=y;for(const f of timers.values())f()},ui:()=>ui,notify:(overrides={})=>window.dispatchEvent({type:'tarot-breaker:stage3-session-ended',detail:{id:9,completed:true,restored:true,running:false,scene:{},...overrides}})};
}
async function flush(n=60){for(let i=0;i<n;i++)await Promise.resolve();}
async function begin(h){h.notify();await flush();assert.equal(h.window.TarotStarGateAftermath.getState().state,'CHECK_COMPANIONS');}
async function drive(h,done,max=1000){for(let i=0;i<max&&!done();i++){if(h.shown.length>h.advancedCount){h.ui().advance();h.advancedCount++;}await flush(8);}assert.ok(done(),'dialogue did not reach expected state');}

test('Aftermath is absent from ordinary routes',()=>{const h=harness({dev:false});h.notify();assert.equal(h.window.TarotStarGateAftermath,undefined);assert.deepEqual(h.calls,[])});

test('present return reveals companions and gives no explicit talk prompt',async()=>{const h=harness();h.notify();assert.deepEqual(h.state().visibility,{shion:1,shiopon:1,lumiere:1});await flush();const r=h.window.TarotStarGateAftermath.getState();assert.equal(r.state,'CHECK_COMPANIONS');assert.equal(h.state().owner,null);assert.equal(h.state().inputSuspended,false);assert.equal(h.state().following,false);assert.equal(h.nodes['aftermath-talk'],undefined);assert.equal(h.nodes['aftermath-talk-label'],undefined);});

test('nearby NPC can be talked to by tapping the actor directly without a prompt',async()=>{const h=harness();await begin(h);const canvas=h.nodes.game;const down={clientX:10,clientY:10,pointerId:7,isPrimary:true,preventDefault(){this.prevented=true},stopImmediatePropagation(){this.stopped=true}};canvas.listeners.pointerdown(down);assert.equal(down.prevented,true);assert.equal(down.stopped,true);const up={...down,prevented:false,stopped:false};canvas.listeners.pointerup(up);await drive(h,()=>h.window.TarotStarGateAftermath.getState().state==='CHECK_COMPANIONS');const r=h.window.TarotStarGateAftermath.getState();assert.deepEqual(JSON.parse(JSON.stringify(r.checked)),['shiopon']);assert.equal(h.state().owner,null);});

test('first individual talk returns control; second talk flows directly into exact v1.3 group and departure',async()=>{
 const h=harness();await begin(h);
 const first=h.window.TarotStarGateAftermath.talk('shiopon');await drive(h,()=>h.window.TarotStarGateAftermath.getState().state==='CHECK_COMPANIONS');assert.equal(await first,true);assert.deepEqual(JSON.parse(JSON.stringify(h.window.TarotStarGateAftermath.getState().checked)),['shiopon']);assert.equal(h.state().owner,null);assert.equal(h.state().following,false);
 h.movePlayer(815,205);const before=h.shown.length;const second=h.window.TarotStarGateAftermath.talk('lumiere');await drive(h,()=>h.window.TarotStarGateAftermath.getState().completed,2500);assert.equal(await second,true);
 const r=h.window.TarotStarGateAftermath.getState();assert.equal(r.completed,true);assert.deepEqual(JSON.parse(JSON.stringify(r.checked)).sort(),['lumiere','shiopon']);assert.equal(h.state().lumiereEnabled,false);assert.equal(h.state().following,true);assert.equal(h.state().owner,null);
 const texts=h.shown.slice(before).map(x=>x.text);assert.ok(texts.includes('二人とも、聞いてくれ。'));assert.ok(texts.includes('……だめだ。思い出せない。'));assert.ok(texts.includes('星の声が……食べられたの。'));assert.ok(texts.includes('星砂で地上に降りよう。'));assert.ok(texts.includes('そこから街を抜けて、歩いて城へ戻る。'));assert.ok(texts.includes('では、私は先に星砂の準備をしてまいります。'));assert.ok(texts.includes('しおぽん、行こう。'));
 assert.ok(!texts.some(t=>/全部、壊れて|未来の自分|カードが/.test(t)));
});

test('either order works and Shiopon consistently calls him シオンさん',async()=>{const h=harness();await begin(h);h.movePlayer(815,205);const p1=h.window.TarotStarGateAftermath.talk('lumiere');await drive(h,()=>h.window.TarotStarGateAftermath.getState().state==='CHECK_COMPANIONS');await p1;h.movePlayer(805,170);const p2=h.window.TarotStarGateAftermath.talk('shiopon');await drive(h,()=>h.window.TarotStarGateAftermath.getState().completed,2500);await p2;const shioponTexts=h.shown.filter(x=>x.actor==='shiopon').map(x=>x.text);assert.ok(shioponTexts.some(t=>t.includes('シオンさん')));assert.ok(shioponTexts.every(t=>!t.includes('シオンさま')));});

test('repeat talk before the second companion does not consume or start the group',async()=>{const h=harness();await begin(h);let p=h.window.TarotStarGateAftermath.talk('shiopon');await drive(h,()=>h.window.TarotStarGateAftermath.getState().state==='CHECK_COMPANIONS');await p;p=h.window.TarotStarGateAftermath.talk('shiopon');await drive(h,()=>h.window.TarotStarGateAftermath.getState().state==='CHECK_COMPANIONS'&&h.shown.at(-1)?.text.includes('ごめんね'));await p;const r=h.window.TarotStarGateAftermath.getState();assert.deepEqual(JSON.parse(JSON.stringify(r.checked)),['shiopon']);assert.equal(r.completed,false);assert.equal(h.state().owner,null);});

test('cancellation from free-check state restores stable visible A0 and original follow',async()=>{const h=harness();await begin(h);assert.equal(h.state().following,false);await h.window.TarotStarGateAftermath.cancel();const r=h.window.TarotStarGateAftermath.getState();assert.equal(r.state,'CANCELLED');assert.equal(r.restored,true);assert.equal(h.state().following,true);assert.deepEqual(h.state().visibility,{shion:1,shiopon:1,lumiere:1});assert.equal(h.state().owner,null);});