const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");
const anomaly=fs.readFileSync("star-gate-anomaly.js","utf8");const interaction=fs.readFileSync("star-gate-interaction.js","utf8");const registry=fs.readFileSync("route-registry.js","utf8");const html=fs.readFileSync("index.html","utf8");
test("anomaly is registered behind Lumiere completion",()=>{assert.match(registry,/garden_star_gate_anomaly/);assert.ok(registry.includes('requires: Object.freeze(["garden_lumiere_gate"])'))});
test("interaction requires canonical Lumiere progress and suppresses completed anomaly",()=>{assert.ok(interaction.includes('isEventCompleted("garden_lumiere_gate")'));assert.ok(interaction.includes('isEventCompleted("garden_star_gate_anomaly")'));assert.ok(!interaction.includes("state?.lumiereDone"))});
test("vision assets and independent card layers are preloaded",()=>{for(const p of ["assets/events/gate-vision/ruins.webp","assets/events/gate-vision/smoke.webp","assets/events/gate-vision/void.webp","shion_card_05_reach.webp","shion_card_dark_aura_01.webp","shion_card_dark_aura_02.webp"])assert.ok(anomaly.includes(p),p);assert.ok(anomaly.includes("Promise.all"));assert.ok(anomaly.includes('class="sga-card"'))});
test("approved ambiguity and aftermath dialogue remain exact",()=>{for(const line of ["――選べ。","星門の拒絶？","……いいえ。拒絶ではありません。","星門の故障とも……違う。","……わかりません。","ひとつ……すごく遠くなった気がする。","……アリエット様のところへ。","星界の声について、私より深く聞き取れる方です。"])assert.ok(anomaly.includes(line),line)});
test("progress completes only after aftermath and runtime is wired",()=>{assert.ok(anomaly.includes('completeEvent("garden_star_gate_anomaly"'));assert.ok(anomaly.indexOf("await aftermath()")<anomaly.indexOf("complete();success=true"));assert.ok(html.includes("star-gate-anomaly.js"));assert.ok(html.includes("star-gate-anomaly.css"))});
test("event owns interaction cleanup",()=>{assert.ok(anomaly.includes("interaction-start"));assert.ok(anomaly.includes("finally{"));assert.ok(anomaly.includes("interaction-end"))});

test("landing restores completed Devil memory into the legacy trigger guard",()=>{const landing=fs.readFileSync("star-country-landing.html","utf8");const restore=landing.indexOf('isEventCompleted("landing_devil_memory")');const guard=landing.indexOf('let devilEventStarted = window.TarotJourney?.get("landingMemoryDone") === true');assert.ok(restore>=0);assert.ok(guard>restore);assert.ok(landing.slice(restore,guard).includes('TarotJourney?.set("landingMemoryDone", true)'))});

test("next-event unlock uses durable Progress after explicit Lumiere completion handoff",()=>{const bridge=fs.readFileSync("garden-progress-observer.js","utf8");const dialogue=fs.readFileSync("dialogue.js","utf8");assert.ok(dialogue.includes('"garden_lumiere_gate"'));assert.ok(dialogue.includes('"tarot-breaker:story-event-complete"'));assert.ok(bridge.includes('progress.completeEvent(eventId, checkpoint)'));assert.ok(interaction.includes('isEventCompleted("garden_lumiere_gate")'));assert.ok(!interaction.includes("state?.lumiereDone"))});
