const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");
const anomaly=fs.readFileSync("star-gate-anomaly.js","utf8");const interaction=fs.readFileSync("star-gate-interaction.js","utf8");const registry=fs.readFileSync("route-registry.js","utf8");const html=fs.readFileSync("index.html","utf8");
test("anomaly is registered behind Lumiere completion",()=>{assert.match(registry,/garden_star_gate_anomaly/);assert.ok(registry.includes('requires: Object.freeze(["garden_lumiere_gate"])'))});
test("interaction requires canonical Lumiere progress and suppresses completed anomaly",()=>{assert.ok(interaction.includes('isEventCompleted("garden_lumiere_gate")'));assert.ok(interaction.includes('isEventCompleted("garden_star_gate_anomaly")'));assert.ok(!interaction.includes("state?.lumiereDone"))});
test("vision assets and independent card layers are preloaded",()=>{for(const p of ["assets/events/gate-vision/ruins.webp","assets/events/gate-vision/smoke.webp","assets/events/gate-vision/void.webp","shion_card_05_reach.webp","shion_card_dark_aura_01.webp","shion_card_dark_aura_02.webp"])assert.ok(anomaly.includes(p),p);assert.ok(anomaly.includes("Promise.all"));assert.ok(anomaly.includes('class="sga-card"'))});
test("approved ambiguity and aftermath dialogue remain exact",()=>{for(const line of ["――選べ。","星門の拒絶？","……いいえ。拒絶ではありません。","星門の故障とも……違う。","……わかりません。","ひとつ……すごく遠くなった気がする。","……アリエット様のところへ。","星界の声について、私より深く聞き取れる方です。"])assert.ok(anomaly.includes(line),line)});
test("progress completes only after aftermath and runtime is wired",()=>{assert.ok(anomaly.includes('completeEvent("garden_star_gate_anomaly"'));assert.ok(anomaly.indexOf("await aftermath()")<anomaly.indexOf("complete();success=true"));assert.ok(html.includes("star-gate-anomaly.js"));assert.ok(html.includes("star-gate-anomaly.css"))});
test("event owns interaction cleanup",()=>{assert.ok(anomaly.includes("interaction-start"));assert.ok(anomaly.includes("finally{"));assert.ok(anomaly.includes("interaction-end"))});

test("landing restores completed Devil memory into the legacy trigger guard",()=>{const landing=fs.readFileSync("star-country-landing.html","utf8");const restore=landing.indexOf('isEventCompleted("landing_devil_memory")');const guard=landing.indexOf('let devilEventStarted = window.TarotJourney?.get("landingMemoryDone") === true');assert.ok(restore>=0);assert.ok(guard>restore);assert.ok(landing.slice(restore,guard).includes('TarotJourney?.set("landingMemoryDone", true)'))});

test("next-event unlock uses durable Progress after explicit Lumiere completion handoff",()=>{const bridge=fs.readFileSync("garden-progress-observer.js","utf8");const dialogue=fs.readFileSync("dialogue.js","utf8");assert.ok(dialogue.includes('"garden_lumiere_gate"'));assert.ok(dialogue.includes('"tarot-breaker:story-event-complete"'));assert.ok(bridge.includes('progress.completeEvent(eventId, checkpoint)'));assert.ok(interaction.includes('isEventCompleted("garden_lumiere_gate")'));assert.ok(!interaction.includes("state?.lumiereDone"))});

test("gate choice requires close approach and owns the movement lock",()=>{assert.match(interaction,/const ACTIVE_RADIUS = 46;/);assert.match(interaction,/garden_star_gate_prompt/);assert.match(interaction,/tarot-breaker:interaction-start/);assert.match(interaction,/hidePrompt\(\{ unlock: false \}\)/);assert.match(interaction,/tarot-breaker:interaction-end/)});

test("anomaly validates durable Progress before starting and keeps one continuous interaction lock",()=>{assert.match(anomaly,/const loaded=p\.load\(\);if\(loaded\.status!==\"valid\"/);assert.match(anomaly,/promptLock===true/);assert.match(anomaly,/if\(!promptLocked\)/);assert.match(anomaly,/const release=interactionOwned\|\|/)});
test("reversal does not synthesize an unauthored low resonance sound",()=>{assert.doesNotMatch(anomaly,/playbackRate\s*=|se\.volume\s*=/)});
test("card ascent hands off to floating without removing ascent state",()=>{assert.doesNotMatch(anomaly,/classList\.remove\(\"ascend\"\)/);const css=fs.readFileSync("star-gate-anomaly.css","utf8");assert.match(css,/@keyframes sgaFloat\{from\{transform:translate3d\(-50%,-38vh/)});

test("cinematic contract pans camera without moving Shion and surveys ruins before card phase",()=>{const game=fs.readFileSync("game.js","utf8");assert.match(game,/TarotCinematicCamera/);assert.match(game,/cinematicCamera\.active/);assert.match(game,/returnToPlayer/);assert.match(game,/TarotActorVisibility/);assert.match(anomaly,/camera\.panTo\(\{x:810,y:105\},1500\)/);assert.match(anomaly,/sga-flow-down/);assert.match(anomaly,/sga-sephirot-lit/);assert.match(anomaly,/sga-flow-up/);assert.match(anomaly,/fadeNpc\("shiopon"\)/);assert.match(anomaly,/fadeNpc\("lumiere"\)/);assert.match(anomaly,/survey-fountain/);assert.match(anomaly,/survey-upper/);assert.match(anomaly,/survey-gate/);assert.ok(anomaly.indexOf("survey-gate")<anomaly.indexOf("setShion(1)"))});
